local items = require "prototypes.items"
local entities = require "prototypes.entities"
local recipes = require "prototypes.recipes"
local technologies = require "prototypes.technologies"
local signals = require "prototypes.signals"
