data:extend({
    {
        type="item-subgroup",
        name="router-signals",
        order="h[router-signals]",
        group="signals"
    },
    {
        type="virtual-signal",
        name="router-signal-default",
        subgroup="router-signals",
        order="h[router-signals]-a[default]",
        icon="__router__/graphics/default.png",
        icon_size=128,
        icon_mipmaps=3
    },
    {
        type="virtual-signal",
        name="router-signal-link",
        subgroup="router-signals",
        order="h[router-signals]-b[link]",
        icon="__router__/graphics/connected.png",
        icon_size=128,
        icon_mipmaps=3
    },
    {
        type="virtual-signal",
        name="router-signal-leaf",
        subgroup="router-signals",
        order="h[router-signals]-c[leaf]",
        icon="__router__/graphics/leaf.png",
        icon_size=128,
        icon_mipmaps=3
    }
})